- name: "Create '/usr/local/bin/' utility scripts"
  ansible.builtin.template:
    dest: "/usr/local/bin/{{ script_name }}.sh"
    src: "freebsd/{{ script_name }}.j2"
    mode: '755'
    force: true
  become: true
  become_user: root
  loop:
    - 'do_upgrade'
  loop_control:
    loop_var: script_name

