- name: "Create alias 'pkg {{ alias_name }}' in {{ cfg_upgrades_freebsd_pkg_conf_file_path }}"
  ansible.builtin.blockinfile:
    path: "{{ cfg_upgrades_freebsd_pkg_conf_file_path }}"
    insertafter: >-
      ^ALIAS(.*)\{$
    block: '  {{ alias_name }}{{ alias_command }},'
    marker: "# {mark} ANSIBLE MANAGED BLOCK: pkg alias for {{ alias_descrip }}"
    state: present
    create: false
  become: true
  become_user: root

