- name: "Set 'CreateBootEnv' to 'no' in {{ cfg_upgrades_freebsd_update_conf_file_path }}"
  ansible.builtin.blockinfile:
    path: "{{ cfg_upgrades_freebsd_update_conf_file_path }}"
    block: "CreateBootEnv no"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: auto boot env creation"
    state: present
    create: false
  become: true
  become_user: root

